name: tests-ci

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node.js & pnpm
        uses: ./.github/actions/setup

      - name: Compile Lingui catalogs
        run: pnpm i18n:compile

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint
